<a href="https://colab.research.google.com/github/Monishpv/monish/blob/main/LinearAlgebraInPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating a matrix using array

In [1]:
import numpy as np
A = np.array([[1, 3, 7, 2],
             [5, 8, -9, 0],
           [6, -7, 11, 12]])
print("A="); print(A)
Atr = np.transpose(A)
print("Transpose of A="); print(Atr)
B = np.array([ [1, 5],
              [4, 5],
              [3, 2],
              [7, 8]])
print("B="); print(B)
Btr = np.transpose(B)
print("Transpose of B="); print(Btr)

A=
[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]
Transpose of A=
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]
B=
[[1 5]
 [4 5]
 [3 2]
 [7 8]]
Transpose of B=
[[1 4 3 7]
 [5 5 2 8]]


Matrix operations

In [2]:
import numpy as np
A = np.matrix([[0, 1],
            [-2, -3]])
B = np.matrix([[1, 0],
             [3, -2]])
C = A + B
print("A+B =", C)
C = A - B
print("A-B =", C)
C = A * B
print("A*B =", C)

A+B = [[ 1  1]
 [ 1 -5]]
A-B = [[-1  1]
 [-5 -1]]
A*B = [[  3  -2]
 [-11   6]]


Matrix Multiplication

In [3]:
import numpy as np
A = np.array([[1, 5, 3],
              [4, 6, 6],
              [3, 8, 9]])
B = np.array([[1, 5, 3, 4],
              [4, 5, 7, 8],
              [7, 8, 9, 3]])
C = np.array([[1],
              [4],
             [3]])
D = np.array([[1, 5, 3]])
M = np.matmul(A,B)
print("M=", M)
#M = np.matmul(B,A) # Not Working!
M = np.matmul(A,C)
print("M=", M)
#M = np.matmul(C,A) # Not Working!
M = np.matmul(C,D)
print("M=", M)
M = np.matmul(D,C)
print("M=", M)

M= [[ 42  54  65  53]
 [ 70  98 108  82]
 [ 98 127 146 103]]
M= [[30]
 [46]
 [62]]
M= [[ 1  5  3]
 [ 4 20 12]
 [ 3 15  9]]
M= [[30]]


Transpose Of a Matrix

In [4]:
import numpy as np
A = np.array([[1, 3, 7, 2],
             [5, 8, -9, 0],
           [6, -7, 11, 12]])
print("A="); print(A)
Atr = np.transpose(A)
print("Transpose of A="); print(Atr)
B = np.array([ [1, 5],
              [4, 5],
              [3, 2],
              [7, 8]])
print("B="); print(B)
Btr = np.transpose(B)
print("Transpose of B="); print(Btr)

A=
[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]
Transpose of A=
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]
B=
[[1 5]
 [4 5]
 [3 2]
 [7 8]]
Transpose of B=
[[1 4 3 7]
 [5 5 2 8]]


Determinant Of a Matrix

In [5]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2],
             [3, 4]])
Adet = la.det(A)
print(Adet)
B = np.array([[-1, 3, 0],
              [2, 1, -5],
             [1, 4, -2]])
Bdet = la.det(B)
print(Bdet)

-2.0000000000000004
-21.00000000000001


Inverse Of a Matrix

In [6]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2],
             [3, 4]])
Ainv = la.inv(A)
print(Ainv)
B = np.array([[-1, 3, 0],
              [2, 1, -5],
             [1, 4, -2]])
Binv = la.inv(B)
print(Binv)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-0.85714286 -0.28571429  0.71428571]
 [ 0.04761905 -0.0952381   0.23809524]
 [-0.33333333 -0.33333333  0.33333333]]


Eigen Values

In [7]:
import numpy as np
import numpy.linalg as la
A = np.array([[0, 1],
           [-2, -3]])
Aeig, v = la.eig(A)
print(Aeig)

[-1. -2.]


Solving Linear Equations

In [8]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2],
             [3, 4]])
b = np.array([[5],
             [6]])
Ainv = la.inv(A)
x = Ainv.dot(b)
print(x)

[[-4. ]
 [ 4.5]]


2nd method for solving

In [11]:
x = np.linalg.solve(A,b)
print(x)

[[-4. ]
 [ 4.5]]
