<a href="https://colab.research.google.com/github/Monishpv/monish/blob/main/pushingtogithub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing the libraries

In [ ]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer



importing the data 

In [ ]:
data= pd.read_csv('Data.csv')
x= data.iloc[:,:-1].values
y= data.iloc[:,-1].values
print(x)
print(y)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


filling the missing values

In [ ]:
imputer= SimpleImputer(missing_values=np.NaN, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]= imputer.transform(x[:,1:3]) 
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


encoding the missing values 

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers= [('encoders', OneHotEncoder(), [0])], remainder= 'passthrough')
x= np.array(ct.fit_transform(x))
print(x)



[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


encoding independent values 

In [ ]:
from pandas.core.arrays.interval import le
from sklearn.preprocessing import LabelEncoder

le= LabelEncoder()
y= le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


TrainSet and TestSet Splitting

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=2, random_state= 1)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


feature scaling 

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train[:,3:]= sc.fit_transform
(x_train[:,3:])
x_test[:,3:]=sc.transform
(x_test[:,3:])
print(x_train)
print(x_test)


[[0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 1.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [1.0 0.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [1.0 0.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 1.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound met